import axios from 'axios';

const API_BASE_URL = '/api';

export interface UploadResponse {
  filename: string;
  filepath: string;
  file_type: 'video' | 'image';
}

export interface TaskResponse {
  task_id: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  progress: number;
  output_path: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface FaceSwapRequest {
  task_id: string;
  source_face_path: string;
  target_video_path: string;
}

export interface FaceSwapResponse {
  task_id: string;
  status: string;
  message: string;
}

// Upload a file (video or image)
export async function uploadFile(file: File): Promise<UploadResponse> {
  const formData = new FormData();
  formData.append('file', file);

  const response = await axios.post<UploadResponse>(
    `${API_BASE_URL}/upload`,
    formData,
    {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    }
  );

  return response.data;
}

// Start face swap processing
export async function startFaceSwap(
  sourceFacePath: string,
  targetVideoPath: string
): Promise<FaceSwapResponse> {
  const response = await axios.post<FaceSwapResponse>(
    `${API_BASE_URL}/faceswap`,
    {
      task_id: '',  // Will be generated by backend
      source_face_path: sourceFacePath,
      target_video_path: targetVideoPath,
    }
  );

  return response.data;
}

// Get task status
export async function getTaskStatus(taskId: string): Promise<TaskResponse> {
  const response = await axios.get<TaskResponse>(
    `${API_BASE_URL}/tasks/${taskId}`
  );

  return response.data;
}

// Get all tasks
export async function getAllTasks(): Promise<TaskResponse[]> {
  const response = await axios.get<TaskResponse[]>(`${API_BASE_URL}/tasks`);
  return response.data;
}

// Get download URL for a task
export function getDownloadUrl(taskId: string): string {
  return `${API_BASE_URL}/download/${taskId}`;
}

// Poll task status until completion
export async function pollTaskStatus(
  taskId: string,
  onProgress: (task: TaskResponse) => void,
  intervalMs: number = 1000
): Promise<TaskResponse> {
  return new Promise((resolve, reject) => {
    const poll = async () => {
      try {
        const task = await getTaskStatus(taskId);
        onProgress(task);

        if (task.status === 'completed') {
          resolve(task);
        } else if (task.status === 'failed') {
          reject(new Error(task.error_message || 'Task failed'));
        } else {
          setTimeout(poll, intervalMs);
        }
      } catch (error) {
        reject(error);
      }
    };

    poll();
  });
}
